name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simplesim:latest
